FROM golang:1.18

# Set environment variables for Go
ENV GO111MODULE=on

WORKDIR /app

RUN go install golang.org/x/tools/cmd/godoc

# Set working directory
WORKDIR /app

# Copy project
COPY . ./src

ENTRYPOINT godoc -http=0.0.0.0:6060 -v -goroot=. 