FROM golang:1.18

# Set environment variables for Go
ENV GO111MODULE=on \
    GOPRIVATE=github.com/pip-services3-gox/*

WORKDIR /app

RUN go install golang.org/x/tools/cmd/godoc@latest

WORKDIR /app

COPY . ./src

ENTRYPOINT godoc -http=0.0.0.0:6060 -v -goroot=. 


