FROM golang:1.18

# Set environment variables for Go
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Install all go_modules
RUN go mod tidy
RUN go mod download

# Build the project
RUN go build -o /go/bin/run .
